begin;
create extension if not exists pgtap with schema extensions;
select plan(37);
insert into auth.users(id) values('b6510000-0000-0000-0000-000000000001'),('b6510000-0000-0000-0000-000000000002') on conflict do nothing;
select ok(not has_function_privilege('anon','phase65_sync_return_sources(text,uuid,integer)','execute'),'anonymous cannot replicate return documents');
select ok(not has_function_privilege('anon','phase65_sync_post_return(text,integer,text,uuid,date,text,jsonb,text)','execute'),'anonymous cannot confirm refunds');
select ok(not has_function_privilege('anon','phase65_sync_void_return(text,integer,text,uuid,text)','execute'),'anonymous cannot void returns');
select ok(not has_function_privilege('anon','phase65_sync_return_snapshot(text,integer,text,uuid)','execute'),'anonymous cannot read return snapshots');
set role authenticated;
select set_config('request.jwt.claims','{"sub":"b6510000-0000-0000-0000-000000000001","role":"authenticated"}',true);
select create_tenant('Offline Returns','offline-returns','Offline Return Shop','or-tenant');
select set_config('or.tenant',current_tenant_id()::text,false);
select set_config('or.shop',(select id::text from shops where tenant_id=current_tenant_id() and is_default limit 1),false);
select register_device('or-till','test');
select register_device('or-other-till','test');
insert into customers(tenant_id,name,client_id) values(current_tenant_id(),'Offline Return Customer','or-customer');
select set_config('or.customer',(select id::text from customers where client_id='or-customer'),false);
insert into items(tenant_id,name,unit1,client_id) values(current_tenant_id(),'Offline Return Item','piece','or-item');
select set_config('or.item',(select id::text from items where client_id='or-item'),false);
select set_item_price(current_setting('or.item')::uuid,current_setting('or.shop')::uuid,'retail',1::smallint,100::bigint,'or-price');
select post_purchase(current_setting('or.shop')::uuid,null,'OR-SEED','2026-09-15',0,0,'or-purchase',jsonb_build_array(jsonb_build_object('item_id',current_setting('or.item'),'unit_level',1,'qty',10,'unit_price_paise',50)),null);
select set_config('or.purchase',(select id::text from purchase_bills where client_id='or-purchase'),false);
select set_config('or.purchase_line',(select id::text from purchase_bill_items where purchase_bill_id=current_setting('or.purchase')::uuid),false);
select post_sale(current_setting('or.shop')::uuid,current_setting('or.customer')::uuid,'2026-09-15',0,0,'or-sale',jsonb_build_array(jsonb_build_object('item_id',current_setting('or.item'),'unit_level',1,'qty',4,'price_kind','retail')),jsonb_build_array(jsonb_build_object('amount_paise',100,'mode','cash')),null);
select set_config('or.sale',(select id::text from sale_invoices where client_id='or-sale'),false);
select set_config('or.line',(select id::text from sale_invoice_items where sale_invoice_id=current_setting('or.sale')::uuid),false);
select set_config('or.snapshot',phase65_sync_return_sources('or-till',current_setting('or.shop')::uuid,1)::text,false);
select is(jsonb_array_length(current_setting('or.snapshot')::jsonb->'sources'),2,'owner receives sale and purchase snapshots');
select ok(current_setting('or.snapshot')::jsonb->'sources'->0 ? 'lines','source snapshots carry immutable line identities');
select ok(not exists(select 1 from jsonb_array_elements(current_setting('or.snapshot')::jsonb->'sources') s where s ?| array['payments','payment_allocations','cash_refund_paise','balance_credit_paise']),'source replica carries no payment/refund decision ledger');
select is((current_setting('or.snapshot')::jsonb->'sources'->0->'lines'->0->>'returned_qty')::numeric,0::numeric,'offline snapshot initially shows no returned quantity');
-- While one till is disconnected, a different till records another receipt.
select record_customer_payment(current_setting('or.shop')::uuid,current_setting('or.customer')::uuid,'2026-09-15',50,'upi','other till',jsonb_build_array(jsonb_build_object('sale_invoice_id',current_setting('or.sale'),'amount_paise',50)),'or-later-payment');
select set_config('or.confirmation',phase65_sync_post_return('or-till',1,'SALE',current_setting('or.sale')::uuid,'2026-09-15','or-return',jsonb_build_array(jsonb_build_object('sale_invoice_item_id',current_setting('or.line'),'qty',2,'disposition','RETURN_TO_SELLABLE')),null)::text,false);
select is((current_setting('or.confirmation')::jsonb->>'cashRefundPaise')::bigint,150::bigint,'reconnect recomputes cash against current receipts, not offline snapshot');
select is((current_setting('or.confirmation')::jsonb->>'balanceCreditPaise')::bigint,50::bigint,'current unpaid remainder becomes balance credit');
select is((current_setting('or.confirmation')::jsonb->'stock'->0->>'available')::numeric,8::numeric,'confirmation returns authoritative stock after disposition');
select lives_ok($$select phase65_sync_post_return('or-other-till',1,'SALE',current_setting('or.sale')::uuid,'2026-09-15','or-return',jsonb_build_array(jsonb_build_object('sale_invoice_item_id',current_setting('or.line'),'qty',2,'disposition','RETURN_TO_SELLABLE')),null)$$,'lost acknowledgement replay from another registered device is idempotent');
select is((select count(*) from payments where client_id='or-return:refund'),1::bigint,'exactly one deterministic refund payment after replay');
select throws_ok($$select phase65_sync_post_return('or-till',1,'SALE',current_setting('or.sale')::uuid,'2026-09-15','or-over-return',jsonb_build_array(jsonb_build_object('sale_invoice_item_id',current_setting('or.line'),'qty',3,'disposition','RETURN_TO_SELLABLE')),null)$$,null,'sale return quantity exceeds sold quantity','stale offline quantity is rejected at server');
select is((select count(*) from sale_returns where client_id='or-over-return'),0::bigint,'rejected provisional return leaves no financial document');
select throws_ok($$select phase65_sync_return_sources('unknown-device',current_setting('or.shop')::uuid,1)$$,null,'device not registered','unregistered device cannot replicate documents');
select throws_ok($$select phase65_sync_return_sources('or-till',current_setting('or.shop')::uuid,999)$$,null,'sync schema update required','schema mismatch fails before replication');
select throws_ok($$select void_payment((select id from payments where client_id='or-return:refund'))$$,null,'void the return instead of its refund payment','refund cannot be voided independently of its return');
select throws_ok($$select void_payment((select id from payments where client_id='or-later-payment'))$$,null,'void posted returns before voiding refunded receipts','cash refund backing receipt cannot be erased');
select is((select status from payments where client_id='or-later-payment'),'POSTED','failed receipt void rolls back payment and allocation changes');
select lives_ok($$select record_customer_payment(current_setting('or.shop')::uuid,current_setting('or.customer')::uuid,'2026-09-15',200,'cash','retained goods',jsonb_build_array(jsonb_build_object('sale_invoice_id',current_setting('or.sale'),'amount_paise',200)),'or-payment-after-refund')$$,'refunded receipts do not block paying the retained goods later');
select is((select count(*) from customer_invoice_outstanding where sale_invoice_id=current_setting('or.sale')::uuid),0::bigint,'retained invoice can be settled exactly after refund');
select lives_ok($$select phase65_sync_void_return('or-till',1,'SALE',(current_setting('or.confirmation')::jsonb->>'returnId')::uuid,'or-void')$$,'confirmed return can be voided online with a stock acknowledgment');
select set_config('or.void',phase65_sync_void_return('or-till',1,'SALE',(current_setting('or.confirmation')::jsonb->>'returnId')::uuid,'or-void')::text,false);
select is(current_setting('or.void')::jsonb->>'status','VOID','replayed void response is VOID');
select is((current_setting('or.void')::jsonb->'stock'->0->>'available')::numeric,6::numeric,'void acknowledgment contains reversed authoritative stock');
select is((select count(*) from stock_movements where source_id=(current_setting('or.confirmation')::jsonb->>'returnId')::uuid and source_type='SALE_RETURN_VOID'),1::bigint,'void replay creates exactly one reversal');
select throws_ok($$select phase65_sync_void_return('unknown',1,'SALE',(current_setting('or.confirmation')::jsonb->>'returnId')::uuid,'or-void')$$,null,'device not registered','unknown device cannot void');
select is((select status from payments where client_id='or-return:refund'),'VOID','void reverses exactly-once refund payment');
select is(phase65_sync_post_return('or-till',1,'SALE',current_setting('or.sale')::uuid,'2026-09-15','or-return',jsonb_build_array(jsonb_build_object('sale_invoice_item_id',current_setting('or.line'),'qty',2,'disposition','RETURN_TO_SELLABLE')),null)->>'status','VOID','replay after another-device void never confirms an outgoing payout');
select ok((check_invariants()->>'ok')::boolean,'offline confirmation respects all financial and stock invariants');
reset role;
update devices set revoked_at=now() where tenant_id=current_setting('or.tenant')::uuid and device_id='or-till';
set role authenticated;
select throws_ok($$select phase65_sync_return_sources('or-till',current_setting('or.shop')::uuid,1)$$,null,'device revoked','revoked till cannot refresh cached return documents');
select throws_ok($$select phase65_sync_return_snapshot('or-till',1,'SALE',(current_setting('or.confirmation')::jsonb->>'returnId')::uuid)$$,null,'device revoked','revoked till cannot read stock acknowledgment');
select throws_ok($$select phase65_sync_post_return('or-till',1,'SALE',current_setting('or.sale')::uuid,'2026-09-15','or-revoked-return',jsonb_build_array(jsonb_build_object('sale_invoice_item_id',current_setting('or.line'),'qty',1,'disposition','RETURN_TO_SELLABLE')),null)$$,null,'device revoked','revoked till cannot confirm a pending refund');
select is((select count(*) from sale_returns where client_id='or-revoked-return'),0::bigint,'revoked confirmation performs no financial writes');
reset role;
insert into tenant_users(tenant_id,user_id,role,shop_ids,status,client_id) values(current_setting('or.tenant')::uuid,'b6510000-0000-0000-0000-000000000002','cashier',array[current_setting('or.shop')::uuid],'active','or-cashier');
set role authenticated;
select set_config('request.jwt.claims','{"sub":"b6510000-0000-0000-0000-000000000002","role":"authenticated"}',true);
select register_device('or-cashier','test');
select throws_ok($$select phase65_sync_void_return('or-cashier',1,'SALE',(current_setting('or.confirmation')::jsonb->>'returnId')::uuid,'cashier-void')$$,null,'not permitted','cashier cannot void even an already-voided return');
select is(jsonb_array_length(phase65_sync_return_sources('or-cashier',current_setting('or.shop')::uuid,1)->'sources'),1,'cashier receives only sale return sources');
select throws_ok($$select phase65_sync_post_return('or-cashier',1,'PURCHASE',current_setting('or.purchase')::uuid,'2026-09-15','or-cashier-purchase',jsonb_build_array(jsonb_build_object('purchase_bill_item_id',current_setting('or.purchase_line'),'qty',1,'disposition','SUPPLIER_RETURN')),null)$$,null,'not permitted','cashier cannot confirm a valid purchase return');
select * from finish();
rollback;
