begin;
create extension if not exists pgtap with schema extensions;
select plan(22);
insert into auth.users(id) values('b6510000-0000-0000-0000-000000000001'),('b6510000-0000-0000-0000-000000000002') on conflict do nothing;
select ok(not has_function_privilege('anon','phase65_sync_return_sources(text,uuid,integer)','execute'),'anonymous cannot replicate return documents');
select ok(not has_function_privilege('anon','phase65_sync_post_return(text,integer,text,uuid,date,text,jsonb,text)','execute'),'anonymous cannot confirm refunds');
set role authenticated;
select set_config('request.jwt.claims','{"sub":"b6510000-0000-0000-0000-000000000001","role":"authenticated"}',true);
select create_tenant('Offline Returns','offline-returns','Offline Return Shop','or-tenant');
select set_config('or.tenant',current_tenant_id()::text,false);
select set_config('or.shop',(select id::text from shops where tenant_id=current_tenant_id() and is_default limit 1),false);
select register_device('or-till','test');
select register_device('or-other-till','test');
insert into customers(tenant_id,name,client_id) values(current_tenant_id(),'Offline Return Customer','or-customer');
select set_config('or.customer',(select id::text from customers where client_id='or-customer'),false);
insert into items(tenant_id,name,unit1,client_id) values(current_tenant_id(),'Offline Return Item','piece','or-item');
select set_config('or.item',(select id::text from items where client_id='or-item'),false);
select set_item_price(current_setting('or.item')::uuid,current_setting('or.shop')::uuid,'retail',1::smallint,100::bigint,'or-price');
select post_purchase(current_setting('or.shop')::uuid,null,'OR-SEED','2026-09-15',0,0,'or-purchase',jsonb_build_array(jsonb_build_object('item_id',current_setting('or.item'),'unit_level',1,'qty',10,'unit_price_paise',50)),null);
select post_sale(current_setting('or.shop')::uuid,current_setting('or.customer')::uuid,'2026-09-15',0,0,'or-sale',jsonb_build_array(jsonb_build_object('item_id',current_setting('or.item'),'unit_level',1,'qty',4,'price_kind','retail')),jsonb_build_array(jsonb_build_object('amount_paise',100,'mode','cash')),null);
select set_config('or.sale',(select id::text from sale_invoices where client_id='or-sale'),false);
select set_config('or.line',(select id::text from sale_invoice_items where sale_invoice_id=current_setting('or.sale')::uuid),false);
select set_config('or.snapshot',phase65_sync_return_sources('or-till',current_setting('or.shop')::uuid,1)::text,false);
select is(jsonb_array_length(current_setting('or.snapshot')::jsonb->'sources'),2,'owner receives sale and purchase snapshots');
select ok(current_setting('or.snapshot')::jsonb->'sources'->0 ? 'lines','source snapshots carry immutable line identities');
select ok(not (current_setting('or.snapshot')::jsonb ?| array['payments','payment_allocations']),'replica carries no payment allocation ledger');
select is((current_setting('or.snapshot')::jsonb->'sources'->0->'lines'->0->>'returned_qty')::numeric,0::numeric,'offline snapshot initially shows no returned quantity');
-- While one till is disconnected, a different till records another receipt.
select record_customer_payment(current_setting('or.shop')::uuid,current_setting('or.customer')::uuid,'2026-09-15',50,'upi','other till',jsonb_build_array(jsonb_build_object('sale_invoice_id',current_setting('or.sale'),'amount_paise',50)),'or-later-payment');
select set_config('or.confirmation',phase65_sync_post_return('or-till',1,'SALE',current_setting('or.sale')::uuid,'2026-09-15','or-return',jsonb_build_array(jsonb_build_object('sale_invoice_item_id',current_setting('or.line'),'qty',2,'disposition','RETURN_TO_SELLABLE')),null)::text,false);
select is((current_setting('or.confirmation')::jsonb->>'cashRefundPaise')::bigint,150::bigint,'reconnect recomputes cash against current receipts, not offline snapshot');
select is((current_setting('or.confirmation')::jsonb->>'balanceCreditPaise')::bigint,50::bigint,'current unpaid remainder becomes balance credit');
select is((current_setting('or.confirmation')::jsonb->'stock'->0->>'available')::numeric,8::numeric,'confirmation returns authoritative stock after disposition');
select lives_ok($$select phase65_sync_post_return('or-other-till',1,'SALE',current_setting('or.sale')::uuid,'2026-09-15','or-return',jsonb_build_array(jsonb_build_object('sale_invoice_item_id',current_setting('or.line'),'qty',2,'disposition','RETURN_TO_SELLABLE')),null)$$,'lost acknowledgement replay from another registered device is idempotent');
select is((select count(*) from payments where client_id='or-return:refund'),1::bigint,'exactly one deterministic refund payment after replay');
select throws_ok($$select phase65_sync_post_return('or-till',1,'SALE',current_setting('or.sale')::uuid,'2026-09-15','or-over-return',jsonb_build_array(jsonb_build_object('sale_invoice_item_id',current_setting('or.line'),'qty',3,'disposition','RETURN_TO_SELLABLE')),null)$$,null,'sale return quantity exceeds sold quantity','stale offline quantity is rejected at server');
select is((select count(*) from sale_returns where client_id='or-over-return'),0::bigint,'rejected provisional return leaves no financial document');
select throws_ok($$select phase65_sync_return_sources('unknown-device',current_setting('or.shop')::uuid,1)$$,null,'device not registered','unregistered device cannot replicate documents');
select throws_ok($$select phase65_sync_return_sources('or-till',current_setting('or.shop')::uuid,999)$$,null,'sync schema update required','schema mismatch fails before replication');
select lives_ok($$select record_customer_payment(current_setting('or.shop')::uuid,current_setting('or.customer')::uuid,'2026-09-15',200,'cash','retained goods',jsonb_build_array(jsonb_build_object('sale_invoice_id',current_setting('or.sale'),'amount_paise',200)),'or-payment-after-refund')$$,'refunded receipts do not block paying the retained goods later');
select is((select count(*) from customer_invoice_outstanding where sale_invoice_id=current_setting('or.sale')::uuid),0::bigint,'retained invoice can be settled exactly after refund');
select lives_ok($$select void_return('SALE',(current_setting('or.confirmation')::jsonb->>'returnId')::uuid,'or-void')$$,'confirmed return can be voided online');
select is((select status from payments where client_id='or-return:refund'),'VOID','void reverses exactly-once refund payment');
select ok((check_invariants()->>'ok')::boolean,'offline confirmation respects all financial and stock invariants');
reset role;
insert into tenant_users(tenant_id,user_id,role,shop_ids,status,client_id) values(current_setting('or.tenant')::uuid,'b6510000-0000-0000-0000-000000000002','cashier',array[current_setting('or.shop')::uuid],'active','or-cashier');
set role authenticated;
select set_config('request.jwt.claims','{"sub":"b6510000-0000-0000-0000-000000000002","role":"authenticated"}',true);
select register_device('or-cashier','test');
select is(jsonb_array_length(phase65_sync_return_sources('or-cashier',current_setting('or.shop')::uuid,1)->'sources'),1,'cashier receives only sale return sources');
select throws_ok($$select phase65_sync_post_return('or-cashier',1,'PURCHASE',(select id from purchase_bills where client_id='or-purchase'),'2026-09-15','or-cashier-purchase','[]'::jsonb,null)$$,null,'not permitted','cashier cannot confirm a purchase return');
select * from finish();
rollback;
