import { useEffect, useState } from 'preact/hooks';
import {
  checkInvariants, createStockCount, exportTenant, getDayBook, getDefaultShopId, getGstSummary,
  getPartyLedger, getStockValuation, listItems, listParties, listStock, postExpense, postStockCount,
  type DayBookRow, type GstRow, type Item, type Party, type PartyLedgerRow, type StockValueRow
} from '@dsb-pro/adapters';

const rupee=(p:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(p/100);
const today=()=>new Date().toISOString().slice(0,10);
function download(name:string,content:string,type:string){const blob=new Blob([content],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href);}
function csv(rows:Record<string,unknown>[]){if(!rows.length)return '';const keys=Object.keys(rows[0]);const esc=(v:unknown)=>'"'+String(v??'').replaceAll('"','""')+'"';return [keys.map(esc).join(','),...rows.map(r=>keys.map(k=>esc(r[k])).join(','))].join('\n');}

export function ReportsScreen(){
 const [shop,setShop]=useState(''); const [from,setFrom]=useState(today().slice(0,8)+'01'); const [to,setTo]=useState(today());
 const [day,setDay]=useState<DayBookRow[]>([]); const [stock,setStock]=useState<StockValueRow[]>([]); const [gst,setGst]=useState<GstRow[]>([]);
 const [parties,setParties]=useState<Party[]>([]); const [partyId,setPartyId]=useState(''); const [partyLedger,setPartyLedger]=useState<PartyLedgerRow[]>([]);
 const [items,setItems]=useState<Item[]>([]); const [stockQty,setStockQty]=useState<Record<string,number>>({});
 const [countItem,setCountItem]=useState(''); const [counted,setCounted]=useState(''); const [msg,setMsg]=useState('');
 useEffect(()=>{void (async()=>{try{const s=await getDefaultShopId();setShop(s);const [ps,is,ss]=await Promise.all([listParties(),listItems(),listStock(s)]);setParties(ps);setItems(is);setStockQty(Object.fromEntries(ss.map(x=>[x.item_id,Number(x.qty_base)])));}catch(e){setMsg(String(e));}})();},[]);
 async function load(){if(!shop)return;setMsg('Loading…');try{const [d,s,g,i]=await Promise.all([getDayBook(shop,from,to),getStockValuation(shop),getGstSummary(shop,from,to),checkInvariants()]);setDay(d);setStock(s);setGst(g);if(partyId)setPartyLedger(await getPartyLedger(partyId,from,to));setMsg(i.ok?'Invariant check: PASS':'Invariant check: FAIL — stop and investigate');}catch(e){setMsg(String(e));}}
 async function expense(e:Event){e.preventDefault();if(!shop)return;const f=new FormData(e.currentTarget as HTMLFormElement);try{await postExpense(shop,String(f.get('date')),String(f.get('category')),String(f.get('description')),Math.round(Number(f.get('amount'))*100),String(f.get('mode')),null,crypto.randomUUID());setMsg('Expense posted.');(e.currentTarget as HTMLFormElement).reset();await load();}catch(err){setMsg(String(err));}}
 async function saveBackup(){if(!shop)return;try{const data=await exportTenant(shop);download('dsb-pro-backup-'+today()+'.json',JSON.stringify(data,null,2),'application/json');for(const key of ['items','parties','customers','purchases','sales','payments','stockMovements','expenses']){const rows=(data[key]??[]) as Record<string,unknown>[];download('dsb-pro-'+key+'-'+today()+'.csv',csv(rows),'text/csv');}setMsg('JSON + CSV device snapshot saved. Keep a copy off-device too.');}catch(e){setMsg(String(e));}}
 async function countStock(e:Event){e.preventDefault();if(!shop||!countItem||counted==='')return;try{const id=await createStockCount(shop,today(),[{item_id:countItem,counted_qty:Number(counted),reason:'manual physical count'}],'Phase 6 physical count',crypto.randomUUID());await postStockCount(id);setMsg('Stock count posted through the adjustment ledger.');setStockQty(v=>({...v,[countItem]:Number(counted)}));setCounted('');await load();}catch(err){setMsg(String(err));}}
 return <main class="wide"><h1>Reports & recovery</h1><p><a href="/">← Home</a></p>
 <div class="row"><label>From<input type="date" value={from} onInput={e=>setFrom((e.target as HTMLInputElement).value)}/></label><label>To<input type="date" value={to} onInput={e=>setTo((e.target as HTMLInputElement).value)}/></label><button class="primary" onClick={()=>void load()}>Refresh</button><button onClick={()=>void saveBackup()}>Save full JSON + CSV backup</button></div>
 {msg&&<p role="status" class={msg.includes('FAIL')?'alert':''}>{msg}</p>}
 <section class="card"><h2>Post expense</h2><form class="grid-form" onSubmit={e=>void expense(e)}><label>Date<input name="date" type="date" required value={today()}/></label><label>Category<input name="category" required/></label><label>Description<input name="description" required/></label><label>Amount ₹<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>Mode<select name="mode"><option>cash</option><option>upi</option><option>card</option><option>bank</option><option>other</option></select></label><button class="primary">Post expense</button></form></section>
 <section class="card"><h2>Physical stock count</h2><form class="grid-form" onSubmit={e=>void countStock(e)}><label>Item<select value={countItem} onInput={e=>setCountItem((e.target as HTMLSelectElement).value)} required><option value="">Choose…</option>{items.map(i=><option value={i.id}>{i.name} — expected {stockQty[i.id]??0} {i.unit1}</option>)}</select></label><label>Counted base quantity<input type="number" min="0" step="0.000001" value={counted} onInput={e=>setCounted((e.target as HTMLInputElement).value)} required/></label><button class="primary">Post stock count</button></form><p class="muted">Posting is refused if stock changed after the count snapshot, preventing a stale count from overwriting live movements.</p></section>
 <section class="card"><h2>Party ledger</h2><div class="row"><select value={partyId} onInput={e=>setPartyId((e.target as HTMLSelectElement).value)}><option value="">Choose supplier…</option>{parties.map(p=><option value={p.id}>{p.name}</option>)}</select><button onClick={()=>void load()}>Load ledger</button></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Document</th><th>Debit</th><th>Credit</th><th>Balance</th></tr></thead><tbody>{partyLedger.map(r=><tr><td>{r.business_date}</td><td>{r.entry_type}</td><td>{r.document}</td><td>{rupee(r.debit_paise)}</td><td>{rupee(r.credit_paise)}</td><td>{rupee(r.running_balance_paise)}</td></tr>)}</tbody></table></div></section>
 <section class="card"><h2>Day book</h2><div class="table-wrap"><table><thead><tr><th>Date</th><th>Sales</th><th>Purchases</th><th>Receipts</th><th>Payments</th><th>Expenses</th><th>Net cash flow</th></tr></thead><tbody>{day.map(r=><tr><td>{r.business_date}</td><td>{rupee(r.sales_paise)}</td><td>{rupee(r.purchases_paise)}</td><td>{rupee(r.receipts_paise)}</td><td>{rupee(r.payments_paise)}</td><td>{rupee(r.expenses_paise)}</td><td>{rupee(r.net_cashflow_paise)}</td></tr>)}</tbody></table></div></section>
 <section class="card"><h2>Stock valuation</h2><div class="table-wrap"><table><thead><tr><th>Item</th><th>Qty base</th><th>Last cost</th><th>Value</th></tr></thead><tbody>{stock.map(r=><tr><td>{r.item_name}</td><td>{r.qty_base}</td><td>{rupee(r.cost_paise)}</td><td>{rupee(r.value_paise)}</td></tr>)}</tbody></table></div></section>
 <section class="card"><h2>GST summary</h2><p class="muted">Derived from immutable tax-rate snapshots. This is a bookkeeping summary, not filing advice.</p><div class="table-wrap"><table><thead><tr><th>Rate</th><th>Taxable sales</th><th>Gross sales</th><th>Taxable purchases</th><th>Gross purchases</th></tr></thead><tbody>{gst.map(r=><tr><td>{(r.tax_rate_bp/100).toFixed(2)}%</td><td>{rupee(r.taxable_sales_paise)}</td><td>{rupee(r.gross_sales_paise)}</td><td>{rupee(r.taxable_purchases_paise)}</td><td>{rupee(r.gross_purchases_paise)}</td></tr>)}</tbody></table></div></section>
 </main>;
}
