import { useEffect, useState } from 'preact/hooks';
import { checkInvariants, exportTenant, getDayBook, getDefaultShopId, getGstSummary, getStockValuation, postExpense, type DayBookRow, type GstRow, type StockValueRow } from '@dsb-pro/adapters';
const rupee=(p:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(p/100);
const today=()=>new Date().toISOString().slice(0,10);
export function ReportsScreen(){
 const [shop,setShop]=useState(''); const [from,setFrom]=useState(today().slice(0,8)+'01'); const [to,setTo]=useState(today());
 const [day,setDay]=useState<DayBookRow[]>([]); const [stock,setStock]=useState<StockValueRow[]>([]); const [gst,setGst]=useState<GstRow[]>([]);
 const [msg,setMsg]=useState('');
 useEffect(()=>{void getDefaultShopId().then(setShop).catch(e=>setMsg(String(e)));},[]);
 async function load(){if(!shop)return;setMsg('Loading…');try{const [d,s,g,i]=await Promise.all([getDayBook(shop,from,to),getStockValuation(shop),getGstSummary(shop,from,to),checkInvariants()]);setDay(d);setStock(s);setGst(g);setMsg(i.ok?'Invariant check: PASS':'Invariant check: FAIL — stop and investigate');}catch(e){setMsg(String(e));}}
 async function expense(e:Event){e.preventDefault();if(!shop)return;const f=new FormData(e.currentTarget as HTMLFormElement);try{await postExpense(shop,String(f.get('date')),String(f.get('category')),String(f.get('description')),Math.round(Number(f.get('amount'))*100),String(f.get('mode')),null,crypto.randomUUID());setMsg('Expense posted.');(e.currentTarget as HTMLFormElement).reset();await load();}catch(err){setMsg(String(err));}}
 async function backup(){if(!shop)return;try{const data=await exportTenant(shop);const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='dsb-pro-backup-'+today()+'.json';a.click();URL.revokeObjectURL(a.href);setMsg('Device snapshot saved. Keep a copy off-device too.');}catch(e){setMsg(String(e));}}
 return <main class="wide"><h1>Reports & recovery</h1><p><a href="/">← Home</a></p>
 <div class="row"><label>From<input type="date" value={from} onInput={e=>setFrom((e.target as HTMLInputElement).value)}/></label><label>To<input type="date" value={to} onInput={e=>setTo((e.target as HTMLInputElement).value)}/></label><button class="primary" onClick={()=>void load()}>Refresh</button><button onClick={()=>void backup()}>Save full JSON backup to device</button></div>
 {msg&&<p role="status" class={msg.includes('FAIL')?'alert':''}>{msg}</p>}
 <section class="card"><h2>Post expense</h2><form class="grid-form" onSubmit={e=>void expense(e)}><label>Date<input name="date" type="date" required value={today()}/></label><label>Category<input name="category" required/></label><label>Description<input name="description" required/></label><label>Amount ₹<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>Mode<select name="mode"><option>cash</option><option>upi</option><option>card</option><option>bank</option><option>other</option></select></label><button class="primary">Post expense</button></form></section>
 <section class="card"><h2>Day book</h2><div class="table-wrap"><table><thead><tr><th>Date</th><th>Sales</th><th>Purchases</th><th>Receipts</th><th>Payments</th><th>Expenses</th><th>Net cash flow</th></tr></thead><tbody>{day.map(r=><tr><td>{r.business_date}</td><td>{rupee(r.sales_paise)}</td><td>{rupee(r.purchases_paise)}</td><td>{rupee(r.receipts_paise)}</td><td>{rupee(r.payments_paise)}</td><td>{rupee(r.expenses_paise)}</td><td>{rupee(r.net_cashflow_paise)}</td></tr>)}</tbody></table></div></section>
 <section class="card"><h2>Stock valuation</h2><div class="table-wrap"><table><thead><tr><th>Item</th><th>Qty base</th><th>Last cost</th><th>Value</th></tr></thead><tbody>{stock.map(r=><tr><td>{r.item_name}</td><td>{r.qty_base}</td><td>{rupee(r.cost_paise)}</td><td>{rupee(r.value_paise)}</td></tr>)}</tbody></table></div></section>
 <section class="card"><h2>GST summary</h2><p class="muted">Derived from tax-rate snapshots stored on finalized purchase/sale lines. Verify filing treatment with your accountant.</p><div class="table-wrap"><table><thead><tr><th>Rate</th><th>Taxable sales</th><th>Gross sales</th><th>Taxable purchases</th><th>Gross purchases</th></tr></thead><tbody>{gst.map(r=><tr><td>{(r.tax_rate_bp/100).toFixed(2)}%</td><td>{rupee(r.taxable_sales_paise)}</td><td>{rupee(r.gross_sales_paise)}</td><td>{rupee(r.taxable_purchases_paise)}</td><td>{rupee(r.gross_purchases_paise)}</td></tr>)}</tbody></table></div></section>
 </main>;
}
