// Entry point for the generated schema types. `types.ts` is GENERATED by
// `pnpm exec supabase gen types typescript --local` against a database at the
// current migrations -- never hand-edit it; regenerate after every migration.
//
// `supabase gen types` marks every RPC argument non-nullable because Postgres
// function signatures carry no nullability. SQL NULL is legal for any argument
// of a non-STRICT function, and our RPCs validate their own inputs, so
// AppDatabase widens RPC Args to `T | null`. Function names, argument names
// and argument types stay fully checked.
import type { Database } from './types';

export type { Database, Json } from './types';

type NullableArgs<F> = {
  [K in keyof F]: F[K] extends { Args: infer A }
    ? A extends Record<string, unknown>
      ? Omit<F[K], 'Args'> & { Args: { [P in keyof A]: A[P] | null } }
      : F[K]
    : F[K];
};

export type AppDatabase = Omit<Database, 'public'> & {
  public: Omit<Database['public'], 'Functions'> & {
    Functions: NullableArgs<Database['public']['Functions']>;
  };
};
