// Emits apps/admin/dist/_headers for Cloudflare Pages (plan §8).
//
// The policy is generated rather than committed as a static file because the
// origins it must allow come from the build environment: the Supabase project
// URL (and its realtime WebSocket origin) and the Sentry DSN. A hardcoded
// policy would silently break the app the first time either changes — the app
// would load and then fail every request, which is a worse failure than not
// having a policy at all.
//
// Note for anyone reading this against plan §8: the full header set is only
// achievable on Cloudflare Pages. GitHub Pages cannot serve repository-
// controlled response headers at all, so the mirror is a reduced-protection
// fallback. That deviation is recorded in the build plan at §19.5.
import { writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dist = join(root, 'apps', 'admin', 'dist');

if (!existsSync(dist)) {
  console.error(`gen-headers: ${dist} does not exist — run the build first.`);
  process.exit(1);
}

/** Origin of a URL, or null when unset/unparseable. */
function originOf(value) {
  if (!value) return null;
  try {
    return new URL(value).origin;
  } catch {
    return null;
  }
}

const supabase = originOf(process.env.VITE_SUPABASE_URL);
// supabase-js opens a realtime WebSocket against the same host over wss.
const supabaseWs = supabase ? supabase.replace(/^https:/, 'wss:') : null;
const sentry = originOf(process.env.VITE_SENTRY_DSN);

const connect = ["'self'", supabase, supabaseWs, sentry].filter(Boolean);
// Item images come back from Supabase Storage; blob:/data: cover locally
// compressed previews before upload.
const img = ["'self'", 'data:', 'blob:', supabase].filter(Boolean);

const csp = [
  "default-src 'self'",
  "base-uri 'self'",
  "object-src 'none'",
  "frame-ancestors 'none'",
  "form-action 'self'",
  "manifest-src 'self'",
  "worker-src 'self'",
  // The production build emits no inline script or style — verified against
  // dist/index.html — so neither 'unsafe-inline' nor 'unsafe-eval' is needed.
  // If a future change introduces one, fix the change, not this policy.
  "script-src 'self'",
  "style-src 'self'",
  "font-src 'self'",
  `img-src ${img.join(' ')}`,
  `connect-src ${connect.join(' ')}`,
  'upgrade-insecure-requests',
].join('; ');

const headers = `# Generated by scripts/gen-headers.mjs at build time. Do not edit by hand.
# Cloudflare Pages only; GitHub Pages cannot serve these (plan §19.5).
/*
  Content-Security-Policy: ${csp}
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: geolocation=(), microphone=(), camera=(), payment=(), usb=(), interest-cohort=()
  Cross-Origin-Opener-Policy: same-origin
  X-Frame-Options: DENY
`;

writeFileSync(join(dist, '_headers'), headers, 'utf8');

console.log('gen-headers: wrote dist/_headers');
console.log(`  supabase : ${supabase ?? '(unset — connect-src will not allow it)'}`);
console.log(`  realtime : ${supabaseWs ?? '(unset)'}`);
console.log(`  sentry   : ${sentry ?? '(unset)'}`);
if (!supabase) {
  console.warn('gen-headers: WARNING — VITE_SUPABASE_URL was not set for this build.');
  console.warn('  The generated policy will block the app from reaching its backend.');
  console.warn('  This is fine for a local build; CI deploy builds always set it.');
}
