export { getSupabaseClient } from './client';
export type { ErrorClass } from './errors';
export { classifyError, errorMessage } from './errors';
export { signUp, signIn, signOut, getSession, onAuthStateChange, isEmailVerified, resendVerificationEmail, resetPasswordForEmail } from './auth';
export type { Session } from './auth';
export type { Membership, Invite, TenantUser } from './tenancy';
export { createTenant, getDefaultShopId, createInvite, revokeInvite, acceptInvite, setUserRole, setUserStatus, removeTenantUser, getCurrentMembership, listTenantUsers, listInvites } from './tenancy';
export type { Device } from './devices';
export { getOrCreateDeviceId, guessDeviceLabel, registerCurrentDevice, listDevices, renameDevice, revokeDevice } from './devices';
export type { Item, Party, StockRow, PurchaseLine } from './masterData';
export { listItems, listParties, createItem, createParty, listStock, postPurchase, voidPurchase, archiveMaster, uploadItemImage, purgeItemImage } from './masterData';
export type { ItemPrice } from './pricing';
export { listCurrentPrices, setItemPrice } from './pricing';
export { replaceItemImage } from './itemImages';
